6 frontend integrate login create account api for both user and advisor
fabrice-niyongabo/child-welfare-portal pull request #41
Opened 2024-05-01 12:28 UTC by joelkwihangana

2024-05-01 13:06 UTC, fabrice-niyongabo requested changes
Check all the comments

2024-05-01 13:06 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      navigate('/');
You need to show a message which displays response from backend. you can use message attribute from signupResponse(This is because users are going to verify their accounts by clicking on a link sent to their email address.)

2024-05-01 13:06 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      navigate('/');
For good UI experience, you can hide everything and show a success icon and then below that icon , you can display message from backend

2024-05-02 04:04 UTC, joelkwihangana commented on backend/src/services/auth.service.ts
Hey! Yeah, I managed to fix the issue by switching from 'bcrypt' to 'bcryptjs'. It's essentially the same API, just pure JavaScript, so no more hassle with native add-ons. All I had to do was change the require calls to 'bcryptjs' and everything else stayed the same. Works like a charm now!

2024-05-02 19:17 UTC, fabrice-niyongabo requested changes
You did not make any change. you just reacted to the comments

2024-05-02 20:29 UTC, fabrice-niyongabo requested changes
Check new comments. you also did not do anything on signup page

2024-05-02 20:29 UTC, fabrice-niyongabo commented on backend/.gitignore
> +.env.development.local
Remove this line. and within .env.development.local, dont push with updated changes (smt, public urls)

2024-05-02 20:29 UTC, fabrice-niyongabo commented on frontend/.gitignore
> +../backend/.env.development.local
remove these two lines(29,30). each project has its own gitignore

2024-05-02 20:29 UTC, fabrice-niyongabo commented on frontend/src/components/authControllers/un-protected-route/index.tsx
> +  console.log(`this is user: ${user}`)
Remove this line

2024-05-02 20:29 UTC, fabrice-niyongabo commented on frontend/src/components/authControllers/un-protected-route/index.tsx
> +      {!user?.token || user.token.trim() === '' ? children : <LoggedInRedirection />}
Keep this line the way it was before. remove the changes that you made.
it will be:
{!user || user.token.trim() === '' ? children : <LoggedInRedirection />}

2024-05-02 20:33 UTC, fabrice-niyongabo commented on backend/.gitignore
> +.env.development.local
Nukuvugango uribusibe changes zose wakoze muri .gitignore yo muri /backend
Noneho muri file ya .env.development.local, ibintu wapastinzemo bishya ukuye kuri watsapp urabisiba then ino file imere uko yariri mbere.

2024-05-02 21:27 UTC, joelkwihangana commented on frontend/src/pages/authentication/signup/index.tsx
> +      navigate('/');
Ehh okay! Now I understand!!

2024-05-03 10:00 UTC, fabrice-niyongabo reviewed
Looks like conflict issues are solved. 
The next steps is to fix singup page

2024-05-03 19:37 UTC, fabrice-niyongabo approved these changes
Check again. And also check login page. there is a component for handling the loading state. <PageLoader /> you need to add that one in this page as well.

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
>  interface ISignupResponse {
This is not how signup response looks like. double check and update this.

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      const { userdata, token,message } = response.data as ISignupResponse;
You only need the message. the rest are useless. remove them  (userdata and token)

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
>        dispatch(signUpUser({ ...userdata, token }));
Remove this line

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
>    const dispatch = useDispatch();
Remove this line

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
Why do I still see:
import { signUpUser } from '../../../redux/actions/user';

import { useDispatch } from 'react-redux';


In this file you do not need to do anything with redux

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +  const [errorresponse, setErrorResponse] = useState<string>('');
Remove this because errorHandler will take care of each and every error that might occur

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      setErrorResponse(error.response?.data?.message);
Remove this line

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      // errorHandler(error);
Uncomment this line

2024-05-03 19:37 UTC, fabrice-niyongabo commented on frontend/src/pages/authentication/signup/index.tsx
> +      // console.log(error.response?.data?.message);
Remove this line

2024-05-03 19:39 UTC, fabrice-niyongabo requested changes
check previous comments before I mistakenly aproved your changes.

2024-05-03 22:27 UTC, joelkwihangana commented
I tried to make some fixes, but the backend issue about email verification persists.
![image](https://github.com/fabrice-niyongabo/child-welfare-portal/assets/85849394/6d5608e7-2df9-4e4e-9cd7-285f3f5b9b6e)

2024-05-04 11:05 UTC, fabrice-niyongabo approved these changes

2024-05-04 11:05 UTC, merged