40 backend parent can be able to delete hisher unproved child
fabrice-niyongabo/child-welfare-portal pull request #53
Opened 2024-05-02 17:00 UTC by iradudemo

This code contains 3 issues

- -Parent can register new child and be approved by Advisor

- parent can be able to delete his/her unproved child

-  Authenticate Register child API & provide its documentation in swagger.ymal

2024-05-02 18:30 UTC, fabrice-niyongabo requested changes
Check all the comments

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/package.json
> +    "nodemon": "^3.1.0",
nodemon must be a dev dependency

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/dtos/advisor.dto.ts
> +export class RegisterAdvisorDto {
Advisor is a normal user. with a role of ADVISOR

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/dtos/child.dto.ts
>    public dateOfBirth: Date;
dateofbirth must be string not a date

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/dtos/child.dto.ts
>    public dateOfBirth: Date;
change this line: 
public dateOfBirth: Date;
to:
public dateOfBirth: string;

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/interfaces/advisor.interface.ts
> +export interface IAdvisor {
Delete this file

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/interfaces/advisor.interface.ts
> +export interface IAdvisor {
Advisor is a normal user with a role of advisor

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/interfaces/child.interface.ts
> +  status:"pending"| "approved"| "rejected"|"unapproved";
Remove unapproved status. we dont need it. child's status must be either pending, approved or rejected.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/interfaces/users.interface.ts
> +export type AdminRole = "admin"
Remove this line. admin role you can get it from TUserRole.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/middlewares/protectRoute.middleware.ts
> +import { AdminRole, TUserRole } from "../interfaces/users.interface";
Remove AdminRole from here. you dont need to do any change within this middleware.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/models/advisor.model.ts
> +import { Schema, Document, model } from "mongoose";
Delete this file. Advisor is a normal user with the role of advisor. consider checking signup API

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/models/child.model.ts
> +      enum: ["pending", "approved", "rejected","unapproved"],
Remove unapproved status

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/routes/v1/advisor.route.ts
> +import express from "express";
The logic within this file is wrong. admin is the only one to register advisor otherwise advisor must register them selves through signup API and be approved by admin.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/routes/v1/users.route.ts
> +import { protectRoute } from "../../middlewares/protectRoute.middleware";
What are you doing withing this file?? it has nothing to do with the tasks that you are working on.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/routes/v1/users.route.ts
> +router.get("/",authMiddleware, controller.getUsers);
?????

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/services/advisor.service.ts
> +import httpStatus from "http-status";
Wrong logic.

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/services/auth.service.ts
> +  console.log("email**************",email)
Remove this. it doing nothing

2024-05-02 18:30 UTC, fabrice-niyongabo commented on backend/src/services/child.service.ts
> +    console.log("findChild",findChild)
remove this log.

2024-05-02 18:44 UTC, iradudemo commented on backend/src/interfaces/advisor.interface.ts
> +export interface IAdvisor {
Sloved

2024-05-02 18:45 UTC, iradudemo commented on backend/src/interfaces/child.interface.ts
> +  status:"pending"| "approved"| "rejected"|"unapproved";
Solved

2024-05-02 19:44 UTC, fabrice-niyongabo requested changes

2024-05-02 19:44 UTC, fabrice-niyongabo commented on backend/src/dtos/child.dto.ts
>    public address: {
Remove this address from dto. idea is that child must be registered by an advisor or parent. so we will use address of logged in user instead of sending it from the request body

2024-05-02 19:44 UTC, fabrice-niyongabo commented on backend/src/services/child.service.ts
Below line 26. 
- make sure to grab the address object from the logged-in user(req.user.address)
- Also if the child is registered by advisor, automatically set the status to approved otherwise pending.

2024-05-02 19:44 UTC, fabrice-niyongabo commented on backend/src/routes/v1/index.ts
>      route: childRoute,
Within this childRoute file, go and protect route the route for adding new child with parent and advisor user roles

2024-05-02 20:01 UTC, iradudemo commented on backend/src/services/child.service.ts
Solved

2024-05-02 20:08 UTC, iradudemo commented on backend/src/routes/v1/index.ts
>      route: childRoute,
Done

2024-05-02 20:37 UTC, fabrice-niyongabo requested changes
Good work, but one thing remaining is that you have to update the registerchildDto and remove address object

2024-05-02 20:40 UTC, fabrice-niyongabo requested changes
final check

2024-05-02 20:40 UTC, fabrice-niyongabo commented on backend/src/dtos/child.dto.ts
>    public address: {
Please remove address object from register child dto

2024-05-02 20:44 UTC, iradudemo commented on backend/src/dtos/child.dto.ts
>    public address: {
The same in model

2024-05-03 09:15 UTC, fabrice-niyongabo reviewed
Good job. how about removing address object in register child dto?

2024-05-03 09:41 UTC, fabrice-niyongabo approved these changes
You can grab a beer now!🍻

2024-05-03 09:42 UTC, merged