11 frontend integrate api for registering new children
fabrice-niyongabo/child-welfare-portal pull request #55
Opened 2024-05-03 14:34 UTC by iradudemo

2024-05-03 15:37 UTC, fabrice-niyongabo requested changes
So far so good, just and extra thing. then I will run it local to see how it works and then approve

2024-05-03 15:37 UTC, fabrice-niyongabo commented on frontend/src/pages/parent/children/new/index.tsx
>      <DefaultLayout>
Below this line (line 89):
Add a component called PageLoader and ether pass in your loading state.
it will be like this:
<PageLoader oper={isLoading} />

2024-05-03 15:50 UTC, iradudemo commented on frontend/src/pages/parent/children/new/index.tsx
>      <DefaultLayout>
Done

2024-05-04 09:09 UTC, fabrice-niyongabo approved these changes
Good job

2024-05-04 09:09 UTC, merged